version: "3.1"

services:
  db-craftdocs:
    hostname: db-craftdocs
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./database/data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./database/seed
        target: /docker-entrypoint-initdb.d
  redis:
    hostname: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - type: bind
        source: ./redis/data
        target: /data
